prep-css-flexbox - Matthew Cha
matt-cha/prep-0922-code-solutions pull request #8
Opened 2022-09-23 18:26 UTC by matt-cha

<img width="1791" alt="display-flex" src="https://user-images.githubusercontent.com/113474295/192033141-2fa0ef5b-7784-4cc7-b15f-a79177b57baa.png">
![align-items](https://user-images.githubusercontent.com/113474295/192033146-0ad3bfc0-fc30-481f-8f3a-be4fb028fc5d.png)
![flex-wrap](https://user-images.githubusercontent.com/113474295/192033148-1df48b40-555c-4ac5-84fe-3db198c27915.png)
![justify-content](https://user-images.githubusercontent.com/113474295/192033150-d16b9730-0904-40e4-a0a6-fee0cc6a8c8a.png)

2022-09-23 18:35 UTC, thebearingedge requested changes
Hi Matthew, please attach the rest of your screenshots to the Pull Request

2022-09-23 18:37 UTC, matt-cha commented
Hi Tim, sorry about that! I think I may need to add them each as an individual comment since adding all 4 at the same time only uploads one

2022-09-23 18:37 UTC, matt-cha commented
![flex-wrap](https://user-images.githubusercontent.com/113474295/192034804-8445c729-ae0f-46f0-8a1a-bc9794b4f772.png)

2022-09-23 18:37 UTC, matt-cha commented
![justify-content](https://user-images.githubusercontent.com/113474295/192034831-9e09eaa8-1e44-4b1e-b9c2-4af3d06101cd.png)

2022-09-23 18:37 UTC, matt-cha commented
![align-items](https://user-images.githubusercontent.com/113474295/192034846-34fe7366-15e4-46fe-8d7b-0d6fdff517c1.png)

2022-09-27 16:21 UTC, thebearingedge requested changes
Hi Matthew! since `flex-basis` is a "flex item" property, you'll want to move all of your `flex-basis` properties to a rule set for `.card-wrapper`. 

Also, when doing fractions in CSS, we always use `calc()` like this, for example:

```css
.card-wrapper {
  flex-basis: calc(100% / 3);
}
```

2022-09-27 16:41 UTC, matt-cha commented
![Screen Shot 2022-09-27 at 9 40 16 AM](https://user-images.githubusercontent.com/113474295/192585785-d28d2c80-19e2-42d7-82b4-70d73459dca4.png)

Uploaded new changes for the .card-wrapper!

2022-09-27 22:55 UTC, thebearingedge requested changes

2022-09-27 22:55 UTC, thebearingedge commented on prep-css-flexbox/flex-wrap.html
> +      flex-basis : calc(100% / 6)
Please check the rest of your code for this fix as well.

2022-09-27 22:56 UTC, thebearingedge commented on prep-css-flexbox/flex-wrap.html
> +      flex-basis : calc(100% / 6)
https://github.com/matt-cha/prep-0922-code-solutions/pull/8/files

2022-09-28 00:21 UTC, matt-cha commented
I believe I have fixed the remaining code thank you for being thorough Tim!

2022-09-28 00:21 UTC, matt-cha commented
![Screen Shot 2022-09-27 at 5 18 19 PM](https://user-images.githubusercontent.com/113474295/192660045-81322d10-3f13-48dc-80f8-55c45f9c50ce.png)

2022-09-28 00:21 UTC, matt-cha commented
![Screen Shot 2022-09-27 at 5 19 13 PM](https://user-images.githubusercontent.com/113474295/192660057-84456605-5347-42ea-951c-56a04c887a2a.png)

2022-09-28 00:29 UTC, thebearingedge approved these changes

2022-09-28 00:36 UTC, merged